theme: jekyll-theme-primer
title: AC 209A Final Project - Sports NBA Analysis
description: NBA Game Probability Prediction and Player Analysis
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
